language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install .
  - nvm install 12.7.0
  - npm install

before_script:
  - touch jnitrace/build/__init__.py

script:
  - pylint jnitrace/jnitrace.py
  - npm run lint

deploy:
  provider: pypi
  user: chame1eon
  password:
    secure: PkNiWyAivXABjKf0Qhf6tTboiEfbELApF7FYbpbEW1jwZ8+L9xcjVyUqfKFV/KXC4BBjp5x0vsL7T0O89A1+puzxIMFDvT8Gr/DXTNGQqcAzSsJv4k5X8VD8bgfCpj3rP4SpdfosDsYmwqFSZxkTLTPkSsggybNVCYocfYR5/aWW9XXzFBFld4AJ0LmqvUSMhxjAC5aekWYRjhqLJO2fs2tLmQn1ClPAi6c6d++aM9Q5SnTEA91kh/EXOcGvME3DLQ6v/DlefqjFlQ3ncanJ93cnjbNnRf2kah7gW4Hcq9/9aS6XyHAr6e5fq7QD1DlC6qJiY0m91Q1OcGCZwWiVfcrrJTotQj3ObAMQv5s//My36ge2uduuByXPsQ4++RUmTpFScCcI1obmsJs4jL97lc/sdes6phaUallx5XUxTFgYLBiHtD5eCkn4TAM3a4HWpC7IlN5C95cBMg6/5BhYKpKsEFCb8KOMviDP5xYJ4VgEyUSf7wTcmg+ZI61LJnwnGT67gZ64EMM05d3zAp0oEg1yVZ0v285knn0bneJQVBh3N4JUiFnDzdxVlA1En327EFZ4FLsKmSZlplhlAKF8BdGjWTbNM3Q/Q8HxYbhyUmGNMuxqsZ7YmJp4IwgV7TmUOiRfTL9AITUPmUrQbMkLNUhI92nR8VDbmyeT/JhgY58=
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
